/**
 * Map action types
 */
export const FETCH_GEOJSON_IN_BOUNDS = 'FETCH_GEOJSON_IN_BOUNDS';
export const FETCH_ALL_GEOJSON = 'FETCH_ALL_GEOJSON';
export const UPDATE_MAP_BOUNDS = 'UPDATE_MAP_BOUNDS';
export const UPDATE_SELECTED_MATERIAL = 'UPDATE_SELECTED_MATERIAL';
export const CLEAR_SELECTED_MATERIAL = 'CLEAR_SELECTED_MATERIAL';

/**
 * Chart action types
 */
export const GET_RAMPS_MATERIALS_IN_BOUNDS = 'GET_RAMPS_MATERIALS_IN_BOUNDS';
export const GET_RAMPS_PER_SIZE_CATEGORY_IN_BOUNDS = 'GET_RAMPS_PER_SIZE_CATEGORY_IN_BOUNDS';